import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/home/Nav";
import Footer from "./components/home/Footer";
import ScrollTop from "./components/Helper/ScrollTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="en">
      <body className={inter.className}>
        <Nav>
        </Nav>

        {children}
        <Footer></Footer>
        <ScrollTop></ScrollTop>
      </body>
    </html>
  );
}
